---
- name: Include variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- include_tasks: "setup-{{ ansible_os_family }}.yml"

- include_tasks: configure.yml

- include_tasks: secure-installation.yml

- name: Add databases.
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default(mysql_collation) }}"
    encoding: "{{ item.encoding | default(mysql_charset) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ mysql_databases }}"

- name: Add users.
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  with_items: "{{ mysql_users }}"
  no_log: true

- include_tasks: replication.yml
