---
- name: Check if MySQL is already installed.
  stat: 
    path: /etc/init.d/mysql
  register: mysql_installed

- name: Update apt cache if not installed
  apt: 
    update_cache: yes
  when: mysql_installed.stat.exists == false

- name: Install MySQL packages.
  apt:
    name: "{{ mysql_packages }}"
    state: present

- name: Stop MySQL after initial install.
  service: 
    name: "{{ mysql_service }}"
    state: stopped
  when: mysql_installed.stat.exists == false

- name: Delete innodb log files after initial install.
  file:
    path: "{{ mysql_datadir }}/{{item}}"
    state: absent
  with_items:
    - "ib_logfile0"
    - "ib_logfile1"
  when: mysql_installed.stat.exists == false
